//go:build !ignore_autogenerated

// zz_generated.deepcopy.go — DeepCopy methods required for runtime.Object.
// Equivalent to controller-gen output; hand-written fallback. If you run
// controller-gen later it will overwrite this file (that's fine).
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *FakeWorkload) DeepCopyInto(out *FakeWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy.
func (in *FakeWorkload) DeepCopy() *FakeWorkload {
	if in == nil {
		return nil
	}
	out := new(FakeWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject satisfies runtime.Object.
func (in *FakeWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *FakeWorkloadList) DeepCopyInto(out *FakeWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]FakeWorkload, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *FakeWorkloadList) DeepCopy() *FakeWorkloadList {
	if in == nil {
		return nil
	}
	out := new(FakeWorkloadList)
	in.DeepCopyInto(out)
	return out
}

func (in *FakeWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *FakeWorkloadSpec) DeepCopyInto(out *FakeWorkloadSpec) {
	*out = *in
}

func (in *FakeWorkloadSpec) DeepCopy() *FakeWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(FakeWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *FakeWorkloadStatus) DeepCopyInto(out *FakeWorkloadStatus) {
	*out = *in
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

func (in *FakeWorkloadStatus) DeepCopy() *FakeWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(FakeWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}
